FROM openshift/origin-release:golang-1.14 as builder

# Add everything
ENV PKG_NAME=github.com/aneeshkp/depgraph
ENV PKG_PATH=/go/src/$PKG_NAME
ENV GO111MODULE=on
RUN mkdir -p $PKG_PATH

COPY . $PKG_PATH/
WORKDIR $PKG_PATH
# RUN go install ./...
RUN ./build.sh



